myapp/auth.py
from flask import Flask, render_template, request, url_for, redirect, session, flash, Blueprint
from flask_login import login_user, login_required, logout_user, current_user
from werkzeug.security import generate_password_hash, check_password_hash
from .models import User
from . import db

auth = Blueprint('auth', __name__, url_prefix='/')

@auth.route("signup", methods=['GET','POST'])
def signup():
    if request.method == 'POST':
        user_email = request.form['email']
        first_name = request.form['firstName']
        password = request.form['password']

        # query for user data
        if db.session.query(User).filter(User.email == user_email).count() != 0:
            flash('An account exists with this email.', category='error')
        else:
            new_user = User(email = user_email, password = generate_password_hash(password, method='sha256'),
            first_name = first_name)
            
            db.session.add(new_user)
            db.session.commit()

            user = User.query.filter_by(email=user_email).first()
            login_user(user, remember=True)
            flash('Account created!', category='success')
            return redirect(url_for('views.home'))
    return render_template('signup.html', user = current_user)

@auth.route("login", methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        email = request.form['email']
        password = request.form['password']

        user = User.query.filter_by(email=email).first()
        
        if user:
            if check_password_hash(user.password, password):
                flash("Logged in successfully!", category="success")
                login_user(user, remember=True)
                return redirect(url_for("views.home"))
            else:
                flash("Incorrect password, please try again.", category="error")
        else:
            flash("Email does not exist.", 'error')
    return render_template('login.html', user = current_user)

@auth.route("logout", methods=['GET', 'POST'])
@login_required
def logout():
    logout_user()
    return redirect(url_for('auth.login'))

myapp/views.py
from flask import render_template, request, url_for, redirect, session
from sqlalchemy import and_
from flask import Blueprint
from flask_login import current_user, login_required
from .models import Inventory, Orders, Order_Items, Payments
from . import db

views = Blueprint('views', __name__, url_prefix='/')

@views.route('/')
def home():
    return render_template('index.html', user = current_user)


@views.route('products/<category>')
def products(category):
    list_products = Inventory.query.filter_by(category=category)
    print(list_products)
    return render_template('products.html', products = list_products, user = current_user, tag = item_nametag, category = category)
    


@views.route('products/<category>/<item_id>')
def product_item(category, item_id):
    get_item = Inventory.query.filter_by(item_id = item_id).first()

    # get related products excluding current
    related_products = Inventory.query.filter(and_(Inventory.category == category, Inventory.item_id != item_id)).limit(4).all()
    return render_template('item.html',user = current_user, item = get_item, tag = item_nametag, related_products = related_products)

@views.route('cart')
def cart():
    return render_template('cart.html', user = current_user)

@views.route('add', methods=['GET', 'POST'])
@login_required
def add():
    if request.method == 'POST':
        item_id = request.form['item_id']
        item_quantity = int(request.form['quantity'])

        get_item = Inventory.query.filter_by(item_id=item_id).first()

        price = float(get_item.price)

        item_dict = {item_id: {
            'name': get_item.item_name + ' ' + item_nametag[get_item.category],
            'item_id': item_id,
            'quantity': item_quantity,
            'price': price,
            'total_price': item_quantity * price
        }}

        cart_total_price = 0
        cart_total_quantity = 0

        if 'cart_item' in session:
            if item_id in session['cart_item']:
                old_quantity = session['cart_item'][item_id]['quantity']
                total_quantity = old_quantity + item_quantity
                session['cart_item'][item_id]['total_price'] = format(total_quantity * price, '.2f')
                session['cart_item'][item_id]['quantity'] = total_quantity
            else:
                session['cart_item'].update(item_dict)

            for key, value in session['cart_item'].items():
                individual_quantity = int(value['quantity'])
                individual_price = float(value['total_price'])
                cart_total_price += individual_price
                cart_total_quantity += individual_quantity
        else:
            session['cart_item'] = item_dict
            cart_total_price = price * item_quantity
            cart_total_quantity = item_quantity

        session['cart_total_price'] = format(cart_total_price, '.2f')
        session['cart_total_quantity'] = cart_total_quantity
        session.modified = True
    return redirect(request.referrer)



@views.route('delete_item/<item_id>')
def delete(item_id):
    print(item_id)
    cart_total_quantity = 0
    cart_total_price = 0

    for i in session['cart_item'].items():
        if i[0] == item_id:
            product = session['cart_item'].pop(i[0], None)
            print(product)
            if 'cart_item' in session:
                for key, value in session['cart_item'].items():
                    individual_quantity = int(session['cart_item'][key]['quantity'])
                    individual_price = float(session['cart_item'][key]['total_price'])
                    cart_total_quantity += individual_quantity
                    cart_total_price += individual_price
            break

    if cart_total_quantity == 0:
        session.clear()
    else:
        session['cart_total_quantity'] = cart_total_quantity
        session['cart_total_price'] = format(cart_total_price, '.2f')
    session.modified = True
    return redirect(request.referrer)

@views.route('order_payment', methods=['POST'])
def order_payment():
    # Payment data
    customer_name = request.form['first_name'] + ' ' + request.form['last_name']
    email = request.form['email']
    address1 = request.form['address1']
    address2 = request.form['address2']
    country = request.form['country']
    state = request.form['state']
    zip_code = request.form['zip_code']
    name_on_card = request.form['name_on_card']
    card_numbers = request.form['card_numbers']
    expiration = request.form['expiration']
    cvv = request.form['cvv']

    # Order
    user_id = current_user.id
    order_total_quantity = session['cart_total_quantity']
    order_total_price = session['cart_total_price']

    new_order = Orders(user_id = user_id, total_quantity = order_total_quantity, total_price = order_total_price)

    db.session.add(new_order)
    db.session.commit()

    # Order Items
    last_order = Orders.query.filter_by(user_id=user_id).order_by(Orders.date.desc()).first()
    last_order_id = last_order = last_order.order_id
    for key, value in session['cart_item'].items():
        item_id = int(key)
        item_price = value['total_price']
        item_quantity = value['quantity']
        order_items = Order_Items(item_id = item_id, order_id = last_order_id, item_quantity = item_quantity, item_total_price = item_price)

        db.session.add(order_items)
        db.session.commit()

    # Payment
    payment_info = Payments(
        user_id = user_id,
        order_id = last_order_id,
        name = customer_name,
        email = email,
        address_one = address1,
        address_two = address2,
        country = country,
        state = state,
        zip_code = zip_code,
        name_on_card = name_on_card,
        card_numbers = card_numbers,
        expiration = expiration,
        cvv = cvv
    )
    db.session.add(payment_info)
    db.session.commit()

    return redirect(url_for('views.order_complete'))

@views.route('order_success', methods=['GET', 'POST'])
def order_complete():
    session.clear()
    return render_template('order_success.html', user = current_user)


item_nametag = {
    "candles":  '- Soy Candle',
    "diffusers": 'Reed Diffuser',
    "soaps": 'Soap Variety'
}

myapp/templates/partials/base.html
<!doctype html>
<html lang="en">
    {% block head %}
    <head>
        <title>{% block title %}{% endblock %}</title>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
        <link rel="stylesheet" href="/static/styles.css" class="href">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.3.0/css/font-awesome.css" class="href">
        {% block link %}{% endblock %}
    </head>
    {% endblock %}
    <body>
    {% block navbar %}

    {% endblock %}
    {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
            {% for category, message in messages %}
                {% if category == 'error' %}
                <div class="alert alert-danger alert-dismissible fade show" role="alert">
                    {{ message }}
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
                {% else %}
                <div class="alert alert-success alert-dismissible fade show" role="alert">
                    {{ message }}
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
                {% endif %}
            {% endfor %}
        {% endif %}
    {% endwith %}
    {% block content %}
    {% endblock %}
    <section class="footer align-items-center justify-content-center w-100">
        <div class="container">
            <div class="row">
                <div class="col-lg-5 col-md-5 col-sm-4 col-xs-12">
                    <ul class="address">
                        <h2>Address</h2>
                        <li>Lancaster, Pennsylvania</li>
                        <li>800-913-7920</li>
                        <li>candleinfo@gmail.com</li>
                    </ul>
                </div>
                <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12">
                    <ul class="contact">
                        <h2>Contact</h2>
                        <li>Home</li>
                        <li>About</li>
                        <li>Contact</li>
                        <li>Gallery</li>
                    </ul>
                </div>
                <div class="col-lg-3 col-md-3 col-sm-4 col-xs-12">
                    <ul class="social">
                        <h2>Social</h2>
                        <li>
                            <i class="fa fa-facebook fa-2x"></i>
                       </li>
                       <li>
                            <i class="fa fa-youtube fa-2x"></i>
                       </li>
                       <li>
                            <i class="fa fa-pinterest fa-2x"></i>
                       </li>
                       <li>
                            <i class="fa fa-google-plus fa-2x"></i>
                      </li>
                    </ul>
                </div>
            </div>
        </div>
    </section>
    <script src="{{url_for('static', filename='form_validation.js')}}"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
    </body>
</html>

myapp/templates/partials/nav.html
{% extends '/partials/base.html' %}
{% block navbar %}
<nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">
      <a class="navbar-brand" href="/">Luminaire</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="/">Home</a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Shop
            </a>
            <ul class="dropdown-menu">
              <li><a class="dropdown-item" href="/products/candles">Candles</a></li>
              <li><a class="dropdown-item" href="/products/diffusers">Reed Diffusers</a></li>
              <li><a class="dropdown-item" href="/products/soaps">Soaps & Lotions</a></li>
            </ul>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">About</a>
          </li>
        </ul>
        <ul class="navbar-nav d-flex flex-row me-1 align-items-center">
          {% if user.is_authenticated %}
            {% if 'cart_item' in session %}
            <li class="nav-item me-3 me-lg-0 d-none d-lg-block">
              <a href="{{url_for('views.cart')}}">
                <button class="btn btn-outline-dark" type="submit">
                    <i class="fa fa-shopping-cart me-1"></i>
                      Cart
                    <span class="badge bg-dark text-white ms-1 rounded-pill">{{ session['cart_total_quantity'] }}</span>
                </button>
              </a>
            </li>
            {% endif %}
            <li class="nav-item me-3 me-lg-0">
              <a class="nav-link" href="{{url_for('auth.logout')}}">Logout</a>
            </li>
          {% else %}
          <li class="nav-item me-3 me-lg-0">
            <a class="nav-link" href="{{url_for('auth.signup')}}">Signup</a>
          </li>
          <li class="nav-item me-3 me-lg-0">
            <a class="nav-link" href="{{url_for('auth.login')}}">Login</a>
          </li>
          {% endif %}
        </ul>
      </div>
    </div>
  </nav>
{% endblock %}