myapp/auth.py
from flask import Flask, render_template, request, url_for, redirect, session, flash, Blueprint
from flask_login import login_user, login_required, logout_user, current_user
from werkzeug.security import generate_password_hash, check_password_hash
from .models import User
from . import db

auth = Blueprint('auth', __name__, url_prefix='/')

@auth.route("signup", methods=['GET','POST'])
def signup():
    if request.method == 'POST':
        user_email = request.form['email']
        first_name = request.form['firstName']
        password = request.form['password']

        # query for user data
        if db.session.query(User).filter(User.email == user_email).count() != 0:
            flash('An account exists with this email.', category='error')
        else:
            new_user = User(email = user_email, password = generate_password_hash(password, method='sha256'),
            first_name = first_name)
            
            db.session.add(new_user)
            db.session.commit()

            user = User.query.filter_by(email=user_email).first()
            login_user(user, remember=True)
            flash('Account created!', category='success')
            return redirect(url_for('views.home'))
    return render_template('signup.html', user = current_user)

@auth.route("login", methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        email = request.form['email']
        password = request.form['password']

        user = User.query.filter_by(email=email).first()
        
        if user:
            if check_password_hash(user.password, password):
                flash("Logged in successfully!", category="success")
                login_user(user, remember=True)
                return redirect(url_for("views.home"))
            else:
                flash("Incorrect password, please try again.", category="error")
        else:
            flash("Email does not exist.", 'error')
    return render_template('login.html', user = current_user)

@auth.route("logout", methods=['GET', 'POST'])
@login_required
def logout():
    logout_user()
    return redirect(url_for('auth.login'))

myapp/views.py
from flask import render_template, request, url_for, redirect, session
from sqlalchemy import and_
from flask import Blueprint
from flask_login import current_user, login_required
from .models import Inventory, Orders, Order_Items, Payments
from . import db

views = Blueprint('views', __name__, url_prefix='/')

@views.route('/')
def home():
    return render_template('index.html', user = current_user)


@views.route('products/<category>')
def products(category):
    list_products = Inventory.query.filter_by(category=category)
    print(list_products)
    return render_template('products.html', products = list_products, user = current_user, tag = item_nametag, category = category)
    


@views.route('products/<category>/<item_id>')
def product_item(category, item_id):
    get_item = Inventory.query.filter_by(item_id = item_id).first()

    # get related products excluding current
    related_products = Inventory.query.filter(and_(Inventory.category == category, Inventory.item_id != item_id)).limit(4).all()
    return render_template('item.html',user = current_user, item = get_item, tag = item_nametag, related_products = related_products)

@views.route('cart')
def cart():
    return render_template('cart.html', user = current_user)

@views.route('add', methods=['GET', 'POST'])
@login_required
def add():
    if request.method == 'POST':
        item_id = request.form['item_id']
        item_quantity = int(request.form['quantity'])

        get_item = Inventory.query.filter_by(item_id=item_id).first()

        price = float(get_item.price)

        item_dict = {item_id: {
            'name': get_item.item_name + ' ' + item_nametag[get_item.category],
            'item_id': item_id,
            'quantity': item_quantity,
            'price': price,
            'total_price': item_quantity * price
        }}

        cart_total_price = 0
        cart_total_quantity = 0

        if 'cart_item' in session:
            if item_id in session['cart_item']:
                old_quantity = session['cart_item'][item_id]['quantity']
                total_quantity = old_quantity + item_quantity
                session['cart_item'][item_id]['total_price'] = format(total_quantity * price, '.2f')
                session['cart_item'][item_id]['quantity'] = total_quantity
            else:
                session['cart_item'].update(item_dict)

            for key, value in session['cart_item'].items():
                individual_quantity = int(value['quantity'])
                individual_price = float(value['total_price'])
                cart_total_price += individual_price
                cart_total_quantity += individual_quantity
        else:
            session['cart_item'] = item_dict
            cart_total_price = price * item_quantity
            cart_total_quantity = item_quantity

        session['cart_total_price'] = format(cart_total_price, '.2f')
        session['cart_total_quantity'] = cart_total_quantity
        session.modified = True
    return redirect(request.referrer)



@views.route('delete_item/<item_id>')
def delete(item_id):
    print(item_id)
    cart_total_quantity = 0
    cart_total_price = 0

    for i in session['cart_item'].items():
        if i[0] == item_id:
            product = session['cart_item'].pop(i[0], None)
            print(product)
            if 'cart_item' in session:
                for key, value in session['cart_item'].items():
                    individual_quantity = int(session['cart_item'][key]['quantity'])
                    individual_price = float(session['cart_item'][key]['total_price'])
                    cart_total_quantity += individual_quantity
                    cart_total_price += individual_price
            break

    if cart_total_quantity == 0:
        session.clear()
    else:
        session['cart_total_quantity'] = cart_total_quantity
        session['cart_total_price'] = format(cart_total_price, '.2f')
    session.modified = True
    return redirect(request.referrer)

@views.route('order_payment', methods=['POST'])
def order_payment():
    # Payment data
    customer_name = request.form['first_name'] + ' ' + request.form['last_name']
    email = request.form['email']
    address1 = request.form['address1']
    address2 = request.form['address2']
    country = request.form['country']
    state = request.form['state']
    zip_code = request.form['zip_code']
    name_on_card = request.form['name_on_card']
    card_numbers = request.form['card_numbers']
    expiration = request.form['expiration']
    cvv = request.form['cvv']

    # Order
    user_id = current_user.id
    order_total_quantity = session['cart_total_quantity']
    order_total_price = session['cart_total_price']

    new_order = Orders(user_id = user_id, total_quantity = order_total_quantity, total_price = order_total_price)

    db.session.add(new_order)
    db.session.commit()

    # Order Items
    last_order = Orders.query.filter_by(user_id=user_id).order_by(Orders.date.desc()).first()
    last_order_id = last_order = last_order.order_id
    for key, value in session['cart_item'].items():
        item_id = int(key)
        item_price = value['total_price']
        item_quantity = value['quantity']
        order_items = Order_Items(item_id = item_id, order_id = last_order_id, item_quantity = item_quantity, item_total_price = item_price)

        db.session.add(order_items)
        db.session.commit()

    # Payment
    payment_info = Payments(
        user_id = user_id,
        order_id = last_order_id,
        name = customer_name,
        email = email,
        address_one = address1,
        address_two = address2,
        country = country,
        state = state,
        zip_code = zip_code,
        name_on_card = name_on_card,
        card_numbers = card_numbers,
        expiration = expiration,
        cvv = cvv
    )
    db.session.add(payment_info)
    db.session.commit()

    return redirect(url_for('views.order_complete'))

@views.route('order_success', methods=['GET', 'POST'])
def order_complete():
    session.clear()
    return render_template('order_success.html', user = current_user)


item_nametag = {
    "candles":  '- Soy Candle',
    "diffusers": 'Reed Diffuser',
    "soaps": 'Soap Variety'
}

myapp/templates/cart.html
{% extends '/partials/nav.html' %}
{% block title %} Home {% endblock %}
{% block content %}

<div class="container">
    <main>
      <div class="py-5 text-center">
        <h2>Checkout</h2>
      </div>
  
      <div class="row g-5">
        <div class="col-md-6 col-lg-4 order-md-last">
          <h4 class="d-flex justify-content-between align-items-center mb-3">
            <span class="text-primary">Your cart</span>
            <span class="badge bg-primary rounded-pill">{{ session['cart_total_quantity'] }}</span>
          </h4>
          <ul class="list-group mb-3">
            {% for i in session['cart_item'] %}
            <li class="list-group-item d-flex justify-content-between justify-content-sm-between justify-content-md-between align-items-center lh-sm flex-wrap">
              <div id="name-wrap" class="text-wrap">
                <h6 class="my-0">{{ session['cart_item'][i]['name'] }}</h6>
                <small class="text-body-secondary">Quantity: {{ session['cart_item'][i]['quantity'] }}</small>
              </div>
              <span class="text-body-secondary align-self-center">${{ session['cart_item'][i]['total_price'] }}</span>
              <a href="/delete_item/{{i}}"><button id="removeBtn" class="btn btn-outline-danger btn-xs align-self-center p-1 px-2 rounded-1" ><i class="fa fa-times"></i></button></a>
            </li>
            {% endfor %}
            {% if session['cart_item'] %}
            <li class="list-group-item d-flex justify-content-between">
              <span>Total (USD)</span>
              <strong>${{ session['cart_total_price']}}</strong>
            </li>
            {% else %}
            <li class="list-group-item text-center">Cart is Empty</li>
            {% endif %}
          </ul>          
        </div>
        <div class="col-md-6 col-lg-8">
          <h4 class="mb-3">Billing address</h4>
          <form action="{{url_for('views.order_payment')}}" class="needs-validation" method="POST">
            <div class="row g-3">
              <div class="col-sm-6">
                <label for="firstName" class="form-label">First name</label>
                <input type="text" name="first_name" class="form-control" id="firstName" placeholder="" value="" required>
                <div class="invalid-feedback">
                  Valid first name is required.
                </div>
              </div>
  
              <div class="col-sm-6">
                <label for="lastName" class="form-label">Last name</label>
                <input type="text" name="last_name" class="form-control" id="lastName" placeholder="" value="" required>
                <div class="invalid-feedback">
                  Valid last name is required.
                </div>
              </div>
  
              <div class="col-12">
                <label for="email" class="form-label">Email</label>
                <input type="email" name="email" class="form-control" id="email" placeholder="you@example.com">
                <div class="invalid-feedback">
                  Please enter a valid email address for shipping updates.
                </div>
              </div>
  
              <div class="col-12">
                <label for="address" class="form-label">Address</label>
                <input type="text" name="address1" class="form-control" id="address" placeholder="1234 Main St" required>
                <div class="invalid-feedback">
                  Please enter your shipping address.
                </div>
              </div>
  
              <div class="col-12">
                <label for="address2" class="form-label">Address 2 <span class="text-body-secondary">(Optional)</span></label>
                <input type="text" name="address2" class="form-control" id="address2" placeholder="Apartment or suite">
              </div>
  
              <div class="col-md-5">
                <label for="country" class="form-label">Country</label>
                <select name="country" class="form-select" id="country" required>
                  <option value="">Choose...</option>
                  <option>United States</option>
                </select>
                <div class="invalid-feedback">
                  Please select a valid country.
                </div>
              </div>
  
              <div class="col-md-4">
                <label for="state" class="form-label">State</label>
                <select name="state" class="form-select" id="state" required>
                  <option value="">Choose...</option>
                  <option>California</option>
                </select>
                <div class="invalid-feedback">
                  Please provide a valid state.
                </div>
              </div>
  
              <div class="col-md-3">
                <label for="zip" class="form-label">Zip</label>
                <input name="zip_code" type="text" class="form-control needs-validation" maxlength="5" id="zip" placeholder="" required>
                <div class="invalid-feedback">
                  Zip code required.
                </div>
              </div>
            </div>
  
            <hr class="my-4">
  
            <h4 class="mb-3">Payment</h4>
  
            <div class="my-3">
              <div class="form-check">
                <input id="credit" name="paymentMethod" type="radio" class="form-check-input" checked required>
                <label class="form-check-label" for="credit">Credit card</label>
              </div>
              <div class="form-check">
                <input id="debit" name="paymentMethod" type="radio" class="form-check-input" required>
                <label class="form-check-label" for="debit">Debit card</label>
              </div>
            </div>
  
            <div class="row gy-3">
              <div class="col-md-6">
                <label for="cc-name" class="form-label">Name on card</label>
                <input name="name_on_card" type="text" class="form-control" id="cc-name" placeholder="" required>
                <small class="text-body-secondary">Full name as displayed on card</small>
                <div class="invalid-feedback">
                  Name on card is required
                </div>
              </div>
  
              <div class="col-md-6">
                <label for="cc-number" class="form-label">Credit card number</label>
                <input name="card_numbers" type="text" maxlength=16 class="form-control" id="cc-number" placeholder="" required>
                <div class="invalid-feedback">
                  Credit card number is required
                </div>
              </div>
  
              <div class="col-md-3">
                <label for="cc-expiration" class="form-label">Expiration</label>
                <input name="expiration" type="text" maxlength="4" class="form-control" placeholder="MMYY" id="cc-expiration" placeholder="" required>
                <div class="invalid-feedback">
                  Expiration date required
                </div>
              </div>
  
              <div class="col-md-3">
                <label for="cc-cvv" class="form-label">CVV</label>
                <input name="cvv" type="text" maxlength="3" class="form-control" id="cc-cvv" placeholder="" required>
                <div class="invalid-feedback">
                  Security code required
                </div>
              </div>
            </div>
  
            <hr class="my-4">
  
            <button class="w-100 btn btn-primary btn-lg mb-2" type="submit">Continue to checkout</button>
          </form>
        </div>
      </div>
    </main>
</div>

<div class="footer">
    <div class="container-fluid">
        
    </div>
</div>
{% endblock %}

myapp/templates/index.html
{% extends '/partials/nav.html' %}
{% block title %} Home {% endblock %}
{% block link %}
<link rel="preload" href="/static/images/jumbo_image-min.jpg" as="image">
{% endblock %}
{% block content %}
<div class="jumbotron jumbotron-fluid .img-fluid">
  <container id="hero" class="container-fluid hero-text text-left">
    <div class="hero-text mt-4">
      <h1 class="display-3 ms-4">Luminaire Candles</h1>
      <p class="ms-4">Elevate your senses with our all-natural candles</p>
      <p class="ms-4">Handmade, Organic and Non-Toxic</p>
      <p class="hero-btn ms-4">
        <a class="btn btn-lg" href="#collection" role="button">Shop our collections</a>
      </p>
    </div>
  </container>
</div>
<div id="collection" class="container-fluid text-center">
    <h1>Latest Collections</h1>
</div>
<div class="container">
  <div class="row row-cols-1 row-cols-md-3 g-4">
    <div class="col">
      <a href="/products/candles" class="collection-box">
        <img src="/static/images/collage/candle_collage.jpg" alt="Candles">
        <div class="overlay">
          <div class="overlay-text">Candles</div>
        </div>
      </a>
    </div>
    <div class="col">
      <a href="/products/diffusers" class="collection-box">
        <img src="/static/images/collage/diffuser_collage.jpg" alt="Reed Diffusers">
        <div class="overlay">
          <div class="overlay-text">Reed Diffusers</div>
        </div>
      </a>
    </div>
    <div class="col">
      <a href="/products/soaps" class="collection-box">
        <img src="/static/images/collage/soaps_collage.jpg" alt="Soaps">
        <div class="overlay">
          <div class="overlay-text">Soaps</div>
        </div>
      </a>
    </div>
  </div>
</div>

{% endblock %}

myapp/templates/item.html
{% extends '/partials/nav.html' %}
{% block title %} Products {% endblock %}
{% block content %}
<!-- Item Section -->
<section class="py-5">
    <div class="container px-4 px-lg-5 my-5">
        <div class="row gx-4 gx-lg-5 align-items-center">
            <div class="col-md-6">
                <img class="card-img-top mb-5 mb-md-0 p-3" src="/static/images/products/{{ item.category }}/{{ item.image_src }}" alt="{{ item.category }}" />
            </div>
            <div class="col-md-6">
                <h4 class="display-6 fw-bolder">{{ item.item_name }} {{ tag[item.category] }}</h4>
                <div class="fs-5 mb-3">
                    <span class="text-decoration-line-through">${{ '{:.2f}'.format(item.price + 5) }}</span>
                    <span>${{ item.price }}</span>
                </div>
                <p class="lead">{{ item.description }}</p>
                <form action="/add" method="POST">
                    <input type="hidden" name="item_id" value="{{ item.item_id }}">
                    <div class="d-flex">
                        <input class="form-control text-center me-3" name="quantity" id="inputQuantity" type="num" value="1" onchange="inputUpdate(this.value)" style="max-width: 3rem" />
                        <button class="btn btn-outline-dark flex-shrink-0" type="submit">
                        <i class="bi-cart-fill me-1"></i>
                        Add to cart
                        </button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</section>
<!-- Related Products -->
<section class="py-5 bg-light">
    <div class="container px-4 px-lg-5 mt-5">
        <h2 class="fw-bolder mb-4">Related products</h2>
        <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">
            {% for product in related_products %}
            <div class="col mb-5">
                <div class="card h-100">
                    <div class="badge bg-dark text-white position-absolute" style="top: 0.5rem; right: 0.5rem">Sale</div>
                    <img class="card-img-top related-img" src="/static/images/products/{{ product.category }}/{{ product.image_src }}" alt="..." />
                    <div class="card-body p-4">
                        <div class="text-center">
                            <h5 class="fw-bolder">{{ product.item_name }} {{ tag[product.category]}}</h5>
                            <span class="text-muted text-decoration-line-through">${{ '{:.2f}'.format(item.price + 5) }}</span>
                            ${{ product.price }}
                        </div>
                    </div>
                    <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                        <form class="text-center" action="/add" method="POST">
                            <input type="hidden" name="item_id" value="{{ product.item_id }}">
                            <input type="hidden" name="quantity" value="1">
                            <button class="text-center btn btn-outline-dark mt-auto" type="submit">Add to cart</button>
                        </form>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</section>
{% endblock %}

myapp/templates/login.html
{% extends '/partials/nav.html' %}
{% block title %}Login{% endblock %}
{% block content %}
<div class="row justify-content-center">
    <form action="{{url_for('auth.login')}}" method="POST" class="w-25 p-3">
        <h3 align="center">Login</h3>
        <div class="form-group">
            <label for="email" class="pt-2">Email Address</label>
            <input id="email" type="email" name="email" class="form-control" placeholder="Enter email" />
        </div>
        <div class="form-group">
            <label for="pass" class="pt-2">Password</label>
            <input id="pass" type="password" name="password" class="form-control" placeholder="Enter password" />
        </div>
        <br />
        <button type="Submit" class="btn btn-primary">Submit</button>
    </form>
</div>
{% endblock %}

myapp/templates/order_success.html
{% extends '/partials/nav.html' %}
{% block title %} Order Complete {% endblock %}
{% block content %}
<div class="vh-100 d-flex justify-content-center align-items-center">
    <div>
        <div class="mb-4 text-center">
            <svg xmlns="http://www.w3.org/2000/svg" class="text-success" width="75" height="75"
                fill="currentColor" class="bi bi-check-circle-fill" viewBox="0 0 16 16">
                <path
                    d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zm-3.97-3.03a.75.75 0 0 0-1.08.022L7.477 9.417 5.384 7.323a.75.75 0 0 0-1.06 1.06L6.97 11.03a.75.75 0 0 0 1.079-.02l3.992-4.99a.75.75 0 0 0-.01-1.05z" />
            </svg>
        </div>
        <div class="text-center">
            <h1>Thank You!</h1>
            <p>Your order was completed! You will receive an email in your inbox soon.</p>
            <a id="success-link" href="{{ url_for('views.home') }}"><button class="btn btn-outline-dark">Back Home</button></a>
        </div>
    </div>
</div>
{% endblock %}

myapp/templates/products.html
{% extends '/partials/nav.html' %}
{% block title %} Products {% endblock %}
{% block content %}
<div id="jumbotron-div" class="jumbotron" style="background-image: url('/static/images/products/{{category}}/hero_image.jpg');">
    <div id="product-div" class="container">
        <h1 id="product-header" class="text-center">{{ category.title() }}</h1>
    </div>
</div>
  
<div class="container">
    <div class="row">
        {% for product in products %}
        <div class="col-lg-3 col-md-6 col-sm-12 margin-top-25 mb-3">
            <div class="card h-100 border-0 rounded-0">
                <div id="img-container">
                    <img id="card-img" src="/static/images/products/{{ product.category }}/{{ product.image_src }}" class="card-img-top img-fluid" alt="{{ product.category }}">
                    <a id="img-link" href="/products/{{ product.category }}/{{ product.item_id }}">
                        <div class="middle">
                            <div class="text">View item</div>
                        </div>
                    </a>
                </div>
                <div id="flex-card-body" class="card-body p-0 mt-2">
                  <h5 class="card-title text-left">{{ product.item_name }} {{ tag[category] }}</h5>
                  <p class="card-text">${{ product.price }}</p>
                  <form action="{{url_for('views.add')}}" method="POST">
                    <input type="hidden" name="item_id" value="{{ product.item_id }}">
                    <input type="hidden" name="quantity" value="1">
                    <button id="add-btn" class=" btn btn-block text-black rounded-0 w-100" type="submit">ADD TO CART</button>
                </form>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

myapp/templates/signup.html
{% extends '/partials/nav.html' %}
{% block title %}Sign Up{% endblock %}
{% block content %}
<div class="row justify-content-center sign-up-form">
    <form action="{{url_for('auth.signup')}}" method="POST" class="needs-validation w-25" novalidate>
        <h3 align="center">Sign Up</h3>
        <div class="form-group">
            <label class="pt-2" for="email">Email Address</label>
            <input
            id="email"
            type="email"
            name="email"
            class="form-control" 
            placeholder="Enter email"
            required
            />
            <div class="invalid-feedback">
                Please enter a valid email.
            </div>
        </div>
        <div class="form-group">
            <label class="pt-2" for="email">First Name</label>
            <input
            id="firstName"
            type="text" 
            name="firstName"
            class="form-control" 
            placeholder="Enter first name"
            required
            />
            <div id="invalid-feedback" class="invalid-feedback">
                Please enter first name.
            </div>
        </div>
        <div class="form-group">
            <label class="pt-2" for="pass">Password</label>
            <input
            id="pass"
            type="password" 
            name="password"
            class="form-control" 
            placeholder="Enter password"
            required
            />
            <div id="invalid-confirm" class="invalid-feedback">
                Please enter password.
            </div>
        </div>
        <br />
        <button type="Submit" class="btn btn-primary">Submit</button>
    </form>
</div>
{% endblock %}